### ISSUE TITLE
Paging number bounds

### ISSUE THREAD

**Issue by BrettGAxosoft** [Axosoft/AxoSlackBot#20]
Jordan Wallet [3:47 PM]  
Paging doesn't react well to numbers `<= 0` or `>= 2^31`.
If I give a number in `[2, (2^31)-1]` it tells me it can't find my items, which is ok (I only have 1 page)
If I give a non-number, `1`, or something `<= 0` it says `Here are your items` and gives me the first page, which is also ok
If I give a number `x | x >= 2^31` it gives me `Here are your items {x} of 1` and gives me the first page, which is a little silly (edited)

**Comment by BehnamAxo** [comment]
done
